from inspect import isfunction
from operator import is_
from unicodedata import name
from moviepy.editor import *
from voicevox_options import *
from clip import *


def main():
    # めたんちゃんの設定
    vop = VoicevoxOptions(speakerName="四国めたん", speakerStyle="ノーマル",speed=1.1)
    top = TelopOptions(text_color="pink",text_size=25)
    四国めたん=CharacterVoice(vop,top)
    clip = Clip()
    clip.set_voice("四国めたん", 四国めたん)
    clip.set_voice("四国めたん", 四国めたん)

    # ずんだもんの設定
    vop = VoicevoxOptions(speakerName="ずんだもん", speakerStyle="ノーマル",speed=1.2)
    top = TelopOptions(text_color="#33FF33")
    ずんだもん=CharacterVoice(vop,top)
    clip.set_voice("ずんだもん", ずんだもん)


    しょんぼりずんだもん=CharacterVoice(VoicevoxOptions(speakerName="ずんだもん", speakerStyle="ノーマル",speed=1.2,pitch=-0.05,intonation=0.7),TelopOptions(text_color="#33FF33"))
    clip.set_voice("しょんぼりずんだもん", しょんぼりずんだもん)


    # パワポを画像に変換
    conv_pptx_to_img("./resource/slide/vol1.pptx")
    clip.back_ground(get_slide_path(6))

    # # BGMとメイン動画を設定
    clip.se("./resource/se/イントロ.wav")    
    
    # パワポ1ページ目を表示
    clip.main_visual(get_slide_path(1), is_fullscreen=True)
    clip.wait(0.5)

    # パワポ2ページ目を表示
    clip.main_visual(get_slide_path(2), is_fullscreen=True)
    clip.se("./resource/se/pon.mp3")
    clip.v("ずんだもん", "ずんだもんと")
    clip.wait(0.5)

    # パワポ3ページ目を表示
    clip.main_visual(get_slide_path(3), is_fullscreen=True)
    clip.se("./resource/se/pon.mp3")
    clip.v("四国めたん", "四国めたんの")
    clip.wait(0.2)

    # パワポ4ページ目を表示
    clip.main_visual(get_slide_path(4), is_fullscreen=True)
    clip.se("./resource/se/kansei.mp3")
    clip.v("ずんだもん", f"ずんだ競馬！")
    clip.v("四国めたん", f"ずんだ競馬！!", is_same_timing=True)
    clip.main_visual(get_slide_path(5), is_fullscreen=True)
    clip.wait(2)
    clip.main_visual("", is_fullscreen=True, is_mute=True)

    # # キャラクタの初期設定
    clip.add_character("四国めたん", CharacterImageSettings(x=900,y=320,resize=0.3))
    clip.add_character("ずんだもん", CharacterImageSettings(x=1050,y=320,resize=0.3))
    clip.add_character_style("四国めたん", CharacterImageStyle(name="ノーマル",image_path="./resource/character/四国めたん_ノーマル.png"))
    clip.add_character_style("四国めたん", CharacterImageStyle(name="目そらし",image_path="./resource/character/四国めたん_目そらし.png"))
    clip.add_character_style("四国めたん", CharacterImageStyle(name="イエー",image_path="./resource/character/四国めたん_イエー.png"))
    clip.add_character_style("四国めたん", CharacterImageStyle(name="困り顔",image_path="./resource/character/四国めたん_困り顔.png"))
    clip.add_character_style("四国めたん", CharacterImageStyle(name="汗キャー",image_path="./resource/character/四国めたん_汗キャー.png"))
    clip.add_character_style("四国めたん", CharacterImageStyle(name="ペロ",image_path="./resource/character/四国めたん_ペロ.png"))
    clip.add_character_style("四国めたん", CharacterImageStyle(name="あっ",image_path="./resource/character/四国めたん_あっ.png"))

    clip.add_character_style("ずんだもん", CharacterImageStyle(name="ノーマル",image_path="./resource/character/ずんだもん_ノーマル.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="ビックリ",image_path="./resource/character/ずんだもん_ビックリ.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="イエー",image_path="./resource/character/ずんだもん_イエー.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="右手挙げ",image_path="./resource/character/ずんだもん_右手挙げ.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="困り顔",image_path="./resource/character/ずんだもん_困り顔.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="目とじ考え",image_path="./resource/character/ずんだもん_目とじ考え.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="両手挙げ",image_path="./resource/character/ずんだもん_両手挙げ.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="推理",image_path="./resource/character/ずんだもん_推理.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="ふんす",image_path="./resource/character/ずんだもん_ふんす.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="汗アハハ",image_path="./resource/character/ずんだもん_汗アハハ.png"))
    clip.add_character_style("ずんだもん", CharacterImageStyle(name="涙むふ",image_path="./resource/character/ずんだもん_涙むふ.png"))

    # # キャラクタを初期表示
    clip.char("四国めたん", "ノーマル")
    clip.char("ずんだもん", "ノーマル")

    clip.bgm("./resource/bgm/マーチ.wav")
    clip.main_visual("./resource/movie/中山競馬場.mov",1.1, 1.1,stop=True)

    clip.se("./resource/se/pon.mp3")
    clip.v("ずんだもん", f"秋競馬開幕！")

    clip.v("四国めたん", f"秋競馬開幕！!")
    clip.wait(0.2)

    clip.se("./resource/se/kansei.mp3")
    clip.char("四国めたん", "イエー")
    clip.char("ずんだもん", "イエー")
    clip.v("ずんだもん", f"いえーい！")
    clip.v("四国めたん", f"いえーい！!", is_same_timing=True)
    clip.wait(0.2)

    clip.char("ずんだもん", f"ノーマル")
    clip.char("四国めたん", f"ノーマル")
    clip.v("ずんだもん", f"暑い夏と！熱い夏競馬が終わって、秋競馬が始まったのだ")
    clip.v("ずんだもん", f"札幌、新潟、小倉での開催も終了して、東京での中央競馬開催が再開したのだ",f"札幌、新潟、こくらでの開催も終了して、東京での中央競馬開催が再開したのだ")
    clip.v("ずんだもん", f"(中の人が)比較的中山競馬場と、東京競馬場にはアクセスしやすいので","比較的中山競馬場と、東京競馬場にはアクセスしやすいので")

    clip.char("ずんだもん", "イエー")
    clip.v("ずんだもん", f"折角なので、開幕初日の中山競馬場にやってきたのだ")
    clip.char("ずんだもん", f"ノーマル")


    clip.wait(0.2)
    clip.char("四国めたん", "困り顔")
    clip.v("四国めたん", f"とはいっても、もう14時過ぎでレースも後半戦になってきてるわね")
    clip.wait(0.2)

    clip.char("ずんだもん", "困り顔")
    clip.v("しょんぼりずんだもん", "中の人が競馬予想AIとか作ってるんだけど")
    clip.v("しょんぼりずんだもん", "それの調整とかしたり、昨晩スプラトゥーン3を遅くまでやってたから","それの調整とかしたり、昨晩スプラトゥーンスリーを遅くまでやってたから")
    clip.v("しょんぼりずんだもん", "こんな時間になっちゃったんだよね・・・")
    clip.v("四国めたん", f"あぁ・・・なるほど・・・")
    clip.wait(0.2)

    clip.v("しょんぼりずんだもん", "そのうえ、いつもとルートを変えてきたから迷って・・・")
    clip.v("しょんぼりずんだもん", "いつもより到着に時間がかかっちゃったのだ・・・")
    clip.wait(0.2)

    clip.char("四国めたん", "汗キャー")
    clip.v("四国めたん", f"まぁ、気を取り直して早速入場してみましょう")
    clip.wait(0.2)

    clip.char("ずんだもん", f"ノーマル")
    clip.char("四国めたん", f"ノーマル")
    clip.se("./resource/se/シーン切り替え1.mp3")
    clip.main_visual("./resource/movie/入場口.mov",5, 12)
    clip.v("ずんだもん", f"入場するとスプリンターズステークスの告知をやっていたのだ")
    clip.char("ずんだもん", "困り顔")
    clip.v("ずんだもん", f"できれば、見に行きたいんだけど、入場券の争奪戦がたいへんそうなのだ・・・")
    clip.main_visual("./resource/movie/入場口.mov",12, 12,stop=True)
    clip.wait(1)
    clip.se("./resource/se/シーン切り替え1.mp3")

    clip.set_mark("preview_start")
    clip.main_visual("./resource/movie/焼きそば.mov",2, 4)
    clip.char("ずんだもん", f"イエー")
    clip.v("ずんだもん", f"中にはいって、とりあえずは腹ごしらえ！")
    clip.v("ずんだもん", f"お昼もまだだったしね")
    clip.wait(0.2)

    clip.char("四国めたん", "ペロ")
    clip.v("四国めたん", f"あら、おいしそうな焼きそば、、、と、これはビーr",f"あら、おいしそうな焼きそば、、、と、これはビー")
    clip.main_visual("./resource/movie/焼きそば.mov",4, 4,stop=True)
    clip.char("ずんだもん", "困り顔")
    clip.v("ずんだもん", f"麦ソーダなのだ")
    clip.char("ずんだもん", "困り顔")

    clip.char("四国めたん", "あっ")
    clip.v("四国めたん", f"麦ソーダ")

    clip.wait(0.2)
    clip.char("ずんだもん", "目とじ考え")
    clip.char("四国めたん", "ノーマル")
    clip.v("ずんだもん", f"折角なので、KASUYAの牛すじとか食べたいな。と思っていたんだけど",f"折角なので、カスヤの牛すじとか食べたいな。と思っていたんだけど")

    clip.char("ずんだもん", "困り顔")
    clip.v("ずんだもん", f"お昼ちょっと過ぎだったこともあって、激込みだったのだ")
    clip.wait(0.2)
    clip.set_mark("preview_end")

    clip.preview(preview_range_by_mark=("preview_start","preview_end"))
    
    clip.char("四国めたん", "ペロ")
    clip.v("四国めたん", f"ちょっと落ち着いたら食べに行ってみましょうか",f"ちょっと落ち着いたら、たべに行ってみましょうか")
    clip.char("ずんだもん", f"イエー")
    clip.v("ずんだもん", f"そうするのだ。")
    clip.wait(0.3)

    clip.char("ずんだもん", "目とじ考え")
    clip.v("ずんだもん", f"焼きそばは安定してて、紅しょうがが若干エッジが効いた感じでおいしかったのだ")
    clip.v("四国めたん", f"あら、本当ね")
    clip.wait(0.2)
    clip.char("ずんだもん", "両手挙げ")
    clip.v("ずんだもん", f"視聴者の方々の、中山競馬場オススメの食べ物とかあったら、教えてほしいのだ")
    clip.wait(0.5)

    clip.se("./resource/se/pon.mp3")
    clip.main_visual("./resource/screen/キセキちゃん_ぬいぐるみ.png")
    clip.v("ずんだもん", f"ターフィーショップでキセキちゃんぬいぐるみも買って準備万端！")
    clip.char("四国めたん", "あっ")
    clip.v("四国めたん", f"何時の間に・・・・")
    clip.v("ずんだもん", f"早速パドックを見てから予想するのだ！")
    clip.wait(0.2)

    clip.se("./resource/se/シーン切り替え1.mp3")
    clip.main_visual("./resource/movie/9r_パドック.mov",2,37)
    clip.char("ずんだもん", "イエー")
    clip.char("四国めたん", "イエー")
    clip.v("ずんだもん", f"じゃん！")
    clip.v("四国めたん", f"じゃん！!", is_same_timing=True)
    clip.wait(0.2)
    clip.v("ずんだもん", f"中山9R、アスター賞のパドックなのだ",f"中山9レース、アスター賞のパドックなのだ")
    clip.v("四国めたん", f"開催初日だけあってか、人が一杯いるわね")
    clip.v("四国めたん", f"アスター賞はどんなレースなの？")
    clip.wait(0.2)
    
    clip.char("四国めたん", "ノーマル")
    clip.char("ずんだもん", "推理")
    clip.v("ずんだもん", f"芝の1600m、外回りを10頭で競い合うレースなのだ",f"芝の1600メートル、外回りを10頭で競い合うレースなのだ")
    clip.v("ずんだもん", f"出走できるのは、2歳で1勝しているお馬さんなのだ")
    clip.wait(0.2)
    clip.v("四国めたん", f"夏競馬で新馬戦が始まったばかりだから",f"夏競馬で、しんばせんが始まったばかりだから")
    clip.v("四国めたん", f"早々に1勝を上げた2歳のお馬さんたちのレースなのね")
    clip.wait(0.2)
    clip.v("ずんだもん", f"そうなのだ")
    clip.v("ずんだもん", f"ずんだもんが知ってる限りだと")
    clip.wait(0.2)
    clip.se("./resource/se/pon.mp3")
    clip.main_visual("./resource/movie/9r_パドック.mov",8,8,stop=True)
    clip.char("ずんだもん", "両手挙げ")
    clip.v("ずんだもん", f"2番のシテイタイケツちゃんは")
    clip.v("ずんだもん", f"大井競馬場でデビューしたんだけど、そのレースで")
    clip.v("ずんだもん", f"最後尾のすっごい離されたところから")
    clip.v("ずんだもん", f"最後の直線でぐんぐん伸びてきて")
    clip.v("ずんだもん", f"最終的に2着に3、4馬身差つけて勝っちゃったんだよね")
    clip.v("ずんだもん", f"あまりにも大差を気持ちよくまくったので")
    clip.v("ずんだもん", f"世界的にもそのレースの動画がバズって話題になったのだ")
    clip.wait(0.2)
    clip.char("四国めたん", "イエー")
    clip.v("四国めたん", f"あ、そのニュース、私も見たけど、あの勝ち方は気持ちよかったわね")
    clip.se("./resource/se/シーン切り替え1.mp3")
    clip.main_visual("./resource/movie/9r_パドック.mov",8,37)
    clip.char("四国めたん", "ノーマル")
    clip.v("四国めたん", f"それで、パドックを見て気になるお馬さんは居たの？")
    clip.char("ずんだもん", "推理")
    clip.v("ずんだもん", f"ずんだもんは、パドックでは大体、おしりの筋肉の具合と、毛の艶")
    clip.v("ずんだもん", f"暴れてないかな～。くらいしか見ないんだけど、")
    clip.char("ずんだもん", "イエー")
    clip.v("ずんだもん", f"正直よくわからなかったのだ")
    clip.wait(0.2)
    clip.char("ずんだもん", "右手挙げ")
    clip.v("ずんだもん", f"いかがでしたか？この情報は参考になりましたか？")
    clip.wait(0.2)
    clip.char("四国めたん", "困り顔")
    clip.v("四国めたん", f"なるわけないでしょ。")
    clip.char("ずんだもん", "ノーマル")
    clip.v("ずんだもん", f"人気を参考に買っても良いんだけど、折角なので")
    clip.char("ずんだもん", "両手挙げ")
    clip.v("ずんだもん", f"(中の人が)用意してきたAIちゃんの予想を見てみるのだ。")
    clip.wait(0.5)

    clip.char("ずんだもん", "ノーマル")
    clip.char("四国めたん", "ノーマル")
    clip.se("./resource/se/シーン切り替え1.mp3")
    clip.main_visual("./resource/screen/9r_yosou.png")
    clip.v("ずんだもん", f"AIちゃんの予想はこうなのだ")
    clip.v("四国めたん", f"だいたい人気通りみたいね")
    clip.v("ずんだもん", f"そうみたいだね")
    clip.wait(0.2)
    clip.char("ずんだもん", "推理")
    clip.v("ずんだもん", f"5頭上げてるうちの、5番目なのでなんともなんだけど")
    clip.v("ずんだもん", f"6番人気のアマイちゃんが、若干お買い得なのかな～って気持ちなのだ")
    clip.v("四国めたん", f"へえ")
    clip.wait(0.5)

    clip.se("./resource/se/pon.mp3")
    clip.main_visual("./resource/screen/9r_baken.jpg")
    clip.char("ずんだもん", "イエー")
    clip.char("ずんだもん", "ノーマル")
    clip.back_ground(get_slide_path(7))
    clip.v("ずんだもん", f"ということで、はい、ドン！")


    clip.v("ずんだもん", f"上位人気の中から、見た目が好みだった、")
    clip.v("ずんだもん", f"4人気・10番のシルヴァーゴーストちゃん軸の馬連")
    clip.v("ずんだもん", f"相手は1番人気と3番人気なのだ")
    clip.v("四国めたん", f"2番人気の子は入れなかったのね")
    clip.char("ずんだもん", "困り顔")
    clip.v("ずんだもん", f"購入点数が多くなっちゃうからあきらめたのだ・・・")
    clip.char("ずんだもん", "ノーマル")
    clip.v("ずんだもん", f"軸のシルヴァーゴーストちゃんは、逃げ予想だったので")
    clip.v("ずんだもん", f"開幕日の馬場も合ってるんじゃないかなと予想したのだ")
    clip.wait(0.2)

    clip.v("ずんだもん", f"それと、アマイちゃんの複勝なのだ")
    clip.v("ずんだもん", f"複勝が4倍から10倍なのでなかなかいい感じだね")
    clip.char("四国めたん", "あっ")
    clip.v("四国めたん", f"結構つくわね")
    clip.v("ずんだもん", f"そろそろレースが始まるので見に行ってみるのだ")
    clip.wait(0.2)

    clip.se("./resource/se/シーン切り替え1.mp3")
    clip.main_visual("./resource/screen/keiba_biyori.png")
    clip.char("ずんだもん", "イエー")
    clip.char("四国めたん", "イエー")
    clip.v("ずんだもん", f"競馬！日和ーーーー！")
    clip.v("四国めたん", f"競馬！日和ーーーー！！",is_same_timing=True)
    clip.v("四国めたん", f"ほんと、いい天気。見事な秋晴れね。")
    clip.wait(0.2)
    clip.v("ずんだもん", f"綺麗に晴れたのだ。この開けた青空を浴びるために",f"綺麗に晴れたのだ。このひらけた青空を浴びるために")
    clip.v("ずんだもん", f"競馬場に来てると言っても過言ではないのだ")
    clip.wait(0.5)

    clip.se("./resource/se/シーン切り替え1.mp3")
    clip.main_visual("./resource/movie/9r.mov",0,0,stop=True)
    clip.char("ずんだもん", "ふんす")
    clip.v("ずんだもん", f"そうこうしている間に、9レースが始まるのだ")
    clip.v("ずんだもん", f"9レースは、だいたい第1、第2コーナーの中間くらいからスタート")
    clip.v("ずんだもん", f"結構遠いのだ・・・")

    clip.main_visual("./resource/movie/9r.mov",0,108)
    clip.v("ずんだもん", f"最後にシルヴァーゴーストちゃんがゲートに入って・・・")
    clip.wait(5)
    clip.bgm("./resource/bgm/ロボットのやつ.wav")
    clip.wait(1)
    clip.char("ずんだもん", "イエー")
    clip.char("四国めたん", "イエー")
    clip.v("ずんだもん", f"スタート！")
    clip.v("四国めたん", f"スタート！！",is_same_timing=True)
    clip.wait(0.2)
    clip.char("ずんだもん", "推理")
    clip.char("四国めたん", "ノーマル")
    clip.v("ずんだもん", f"結構いい感じに揃ったスタートなのかな。と思ったんだけど")
    clip.char("ずんだもん", "汗アハハ")
    clip.v("しょんぼりずんだもん", f"思ったスタートじゃ無かったのか、隣のお兄さんがめちゃくちゃ嘆いていたのだ・・・")
    clip.char("四国めたん", "困り顔")
    clip.v("四国めたん", f"かわいそう")
    clip.wait(0.5)
    clip.char("ずんだもん", "ノーマル")
    clip.v("ずんだもん", f"スタートの様子は、後で各々、JRAの公式動画とかみてみてね")
    clip.wait(1)
    clip.char("四国めたん", "ノーマル")
    clip.char("ずんだもん", "困り顔")
    clip.text( f"・・・・・","てんてんてんてんてん")
    clip.char("ずんだもん", "汗アハハ")
    clip.v("ずんだもん", f"あっ・・・・あっ・・・")
    clip.wait(0.2)
    clip.v("四国めたん", f"ずんだもん、どうしたの？")
    clip.wait(0.2)

    clip.v("しょんぼりずんだもん", f"お馬さんまで遠いのと、物陰にかくれちゃって")
    clip.char("ずんだもん", "涙むふ")
    clip.v("しょんぼりずんだもん", f"カメラが早速馬群を見失ったのだ・・・",f"カメラが早速、ばぐんを見失ったのだ・・・")
    clip.char("四国めたん", "困り顔")
    clip.v("四国めたん", f"ええー")
    clip.wait(0.2)

    clip.char("ずんだもん", "困り顔")
    clip.v("しょんぼりずんだもん", f"仕方ないから、見つかるまで、カットするのだ")
    clip.se("./resource/se/シーン切り替え1.mp3")
    clip.main_visual("./resource/movie/9r.mov",69,86)
    clip.char("ずんだもん", "両手挙げ")
    clip.v("ずんだもん", f"あっ！居たのだ！")
    clip.char("四国めたん", "汗キャー")
    clip.v("四国めたん", f"ってもう、最終コーナーじゃない！")
    clip.char("ずんだもん", "ビックリ")
    clip.v("ずんだもん", f"結構縦長で、差が開いている感じなのだ")
    clip.v("ずんだもん", f"先頭は・・・・")
    clip.char("四国めたん", "ノーマル")
    clip.main_visual("./resource/movie/9r.mov",95,108)
    clip.v("ずんだもん", f"5番ドンデンガエシ！")
    clip.v("ずんだもん", f"続いて、10番シルヴァーゴースト")
    clip.v("ずんだもん", f"そしてその後ろが・・・・")
    clip.wait(1)
    clip.char("ずんだもん", f"推理")
    clip.v("ずんだもん", f"ん？")
    clip.text( f"ん？","てんてんてんてんてん")
    clip.wait(1)

    clip.se("./resource/se/カメラのシャッター.mp3")
    clip.main_visual("./resource/movie/9r.mov",103,stop=True)
    clip.wait(1)
    
    clip.se("./resource/se/カメラのシャッター.mp3")
    clip.main_visual("./resource/movie/9r.mov",103.5,stop=True)
    clip.wait(1)
    
    clip.se("./resource/se/カメラのシャッター.mp3")
    clip.main_visual("./resource/movie/9r.mov",104,stop=True)
    clip.wait(1)
    clip.main_visual("./resource/movie/9r.mov",104,108)
    clip.char("ずんだもん", "両手挙げ")
    clip.v("ずんだもん", f"7番アマイちゃんなのだ！")
    clip.se("./resource/se/テッテレー.mp3")
    clip.se("./resource/se/kansei.mp3")
    clip.char("四国めたん", "汗キャー")
    clip.v("四国めたん", f"おおーーー！")
    clip.text( f"・・・・・","てんてんてんてんてん")
    clip.wait(0.5)
    clip.char("ずんだもん", "ビックリ")
    clip.v("ずんだもん", f"・・・・やったか？",)
    clip.wait(0.2)
    clip.char("四国めたん", "あっ")
    clip.v("四国めたん", f"えっ")
    clip.char("ずんだもん", "困り顔")
    clip.v("ずんだもん", f"何か雲行きが怪しいのだ")
    clip.v("四国めたん", f"えー")
    clip.wait(0.2)
    clip.v("ずんだもん", f"ここからの画角だと分かりづらかったんだけど")
    clip.v("ずんだもん", f"内に居た1番のサクセスバラードちゃんと")
    clip.v("ずんだもん", f"ほぼ同じタイミングでゴールしたらしく、写真判定になったのだ")
    clip.char("四国めたん", "困り顔")
    clip.v("四国めたん", f"えー")
    clip.wait(0.2)
    clip.char("ずんだもん", "汗アハハ")
    clip.char("四国めたん", "あっ")
    clip.v("ずんだもん", f"仕方ないからおとなしく結果がでるのをまつのd",f"仕方ないからおとなしく結果がでるのをまつの")
    clip.back_ground(get_slide_path(8))
    clip.se("./resource/se/チーン.mp3")
    clip.main_visual("./resource/screen/9r_kakutei.png")
    clip.v("ずんだもん", f"ｳﾜーーーー!")
    clip.v("四国めたん", f"ｳﾜーーーー",is_same_timing=True)
    clip.wait(0.5)
    clip.v("ずんだもん", f"次回へつづくのだ")
    clip.wait(1)
    # clip.v("ずんだもん", f"もしよければ、いいねや、チャンネル登録、フォローもよろしくね")
    clip.char("ずんだもん", "イエー")
    clip.char("四国めたん", "イエー")
    clip.v("ずんだもん", f"ご視聴、ありがとうございました！")
    clip.v("四国めたん", f"ご視聴、ありがとうございました！！",is_same_timing=True)
    clip.wait(0.5)
    clip.text(f"使用キャラクタ: VOICEVOX: ずんだもん/四国めたん")
    clip.text(f"立ち絵素材: 坂本あひる様")
    clip.text(f"いらすと素材: いらすとや様")
    clip.text(f"効果音: 効果音ラボ様")


if __name__ == "__main__":
    main()

